/* Generated by PDNA. Do not edit by hand; edit the .pdna.json source. */
#include "pdna_effects.h"

const PdnaEffectPreset pdna_effect_stack_land = {
    .voice = {
        .waveform = PDNA_WAVEFORM_TRIANGLE,
        .envelope = { 0.002f, 0.03f, 0.08f, 0.05f, 0.0f, 1.0f, false, true, NULL },
        .volume = 1.0f,
        .pitch_source = { .kind = PDNA_PITCH_SOURCE_NONE },
    },
    .note = 55.0f,
    .velocity = 0.7f,
    .duration_s = 0.08f,
};

const PdnaEffectPreset pdna_effect_perfect_stack = {
    .voice = {
        .waveform = PDNA_WAVEFORM_SINE,
        .envelope = { 0.002f, 0.05f, 0.2f, 0.08f, 0.0f, 1.0f, false, true, NULL },
        .volume = 1.0f,
        .pitch_source = {
            .kind = PDNA_PITCH_SOURCE_MOTION,
            .value.motion = { 0.0f, 7.0f, 0.14f },
        },
    },
    .note = 67.0f,
    .velocity = 0.8f,
    .duration_s = 0.14f,
};

const PdnaEffectPreset pdna_effect_perfect_stack_2 = {
    .voice = {
        .waveform = PDNA_WAVEFORM_SINE,
        .envelope = { 0.002f, 0.05f, 0.2f, 0.08f, 0.0f, 1.0f, false, true, NULL },
        .volume = 1.0f,
        .pitch_source = {
            .kind = PDNA_PITCH_SOURCE_MOTION,
            .value.motion = { 0.0f, 7.0f, 0.14f },
        },
    },
    .note = 70.0f,
    .velocity = 0.8f,
    .duration_s = 0.14f,
};

const PdnaEffectPreset pdna_effect_perfect_growth = {
    .voice = {
        .waveform = PDNA_WAVEFORM_TRIANGLE,
        .envelope = { 0.002f, 0.05f, 0.24f, 0.12f, 0.0f, 1.0f, false, true, NULL },
        .volume = 1.0f,
        .pitch_source = {
            .kind = PDNA_PITCH_SOURCE_MOTION,
            .value.motion = { 0.0f, 9.0f, 0.18f },
        },
    },
    .note = 74.0f,
    .velocity = 0.9f,
    .duration_s = 0.18f,
};

const PdnaEffectPreset pdna_effect_stack_miss = {
    .voice = {
        .waveform = PDNA_WAVEFORM_NOISE,
        .envelope = { 0.001f, 0.04f, 0.0f, 0.08f, 0.0f, 1.0f, false, true, NULL },
        .volume = 1.0f,
        .pitch_source = {
            .kind = PDNA_PITCH_SOURCE_MOTION,
            .value.motion = { 4.0f, -8.0f, 0.16f },
        },
    },
    .note = 42.0f,
    .velocity = 0.85f,
    .duration_s = 0.16f,
};
