/* Generated by PDNA. Do not edit by hand; edit the .pdna.json source. */
#include "pdna_song_1.h"

static const PdnaNoteEvent song_1_lead_notes[] = {
    { 3, 1, 77.0f, 0.7f }, { 4, 1, 76.0f, 0.7f },
    { 5, 1, 77.0f, 0.7f }, { 6, 2, 74.0f, 0.7f },
    { 9, 1, 77.0f, 0.7f }, { 10, 1, 72.0f, 0.7f },
    { 11, 1, 77.0f, 0.7f }, { 12, 14, 71.0f, 0.7f },
    { 35, 1, 76.0f, 0.7f }, { 36, 1, 74.0f, 0.7f },
    { 37, 1, 76.0f, 0.7f }, { 38, 2, 72.0f, 0.7f },
    { 41, 1, 76.0f, 0.7f }, { 42, 1, 71.0f, 0.7f },
    { 43, 1, 76.0f, 0.7f }, { 44, 14, 69.0f, 0.7f },
};

static const PdnaNoteEvent song_1_harmony_notes[] = {
    { 2, 1, 62.0f, 0.7f }, { 6, 1, 62.0f, 0.7f },
    { 9, 1, 62.0f, 0.7f }, { 12, 1, 62.0f, 0.7f },
    { 15, 1, 62.0f, 0.7f }, { 18, 1, 67.0f, 0.7f },
    { 22, 1, 67.0f, 0.7f }, { 25, 1, 67.0f, 0.7f },
    { 28, 1, 67.0f, 0.7f }, { 31, 1, 67.0f, 0.7f },
    { 34, 1, 69.0f, 0.7f }, { 38, 1, 69.0f, 0.7f },
    { 41, 1, 69.0f, 0.7f }, { 44, 1, 69.0f, 0.7f },
    { 47, 1, 69.0f, 0.7f }, { 50, 1, 65.0f, 0.7f },
    { 54, 1, 65.0f, 0.7f }, { 57, 1, 65.0f, 0.7f },
    { 60, 1, 64.0f, 0.7f }, { 63, 1, 64.0f, 0.7f },
};

static const PdnaNoteEvent song_1_bass_notes[] = {
    { 2, 14, 38.0f, 0.7f }, { 18, 8, 43.0f, 0.7f },
    { 34, 14, 45.0f, 0.7f }, { 50, 8, 41.0f, 0.7f },
    { 58, 4, 40.0f, 0.7f },
};

static const PdnaNoteEvent song_1_percussion_notes[] = {
    { 0, 1, 30.0f, 0.7f }, { 4, 1, 36.0f, 0.7f },
    { 8, 1, 30.0f, 0.7f }, { 12, 1, 36.0f, 0.7f },
    { 16, 1, 30.0f, 0.7f }, { 20, 1, 36.0f, 0.7f },
    { 24, 1, 30.0f, 0.7f }, { 28, 1, 36.0f, 0.7f },
    { 32, 1, 30.0f, 0.7f }, { 36, 1, 36.0f, 0.7f },
    { 40, 1, 30.0f, 0.7f }, { 44, 1, 36.0f, 0.7f },
    { 48, 1, 30.0f, 0.7f }, { 52, 1, 36.0f, 0.7f },
    { 56, 1, 30.0f, 0.7f }, { 60, 1, 36.0f, 0.7f },
};

static const PdnaInstrumentVoicePreset song_1_lead_voices[] = {
    {
        .key_range = { 0.0f, 127.0f },
        .voice = {
            .waveform = PDNA_WAVEFORM_SQUARE,
            .envelope = { 0.005f, 0.04f, 0.55f, 0.03f, 0.0f, 1.0f, false, true, NULL },
            .volume = 0.12f,
            .pitch_source = {
                .kind = PDNA_PITCH_SOURCE_VIBRATO,
                .value.vibrato = { PDNA_LFO_SINE, 3.0f, 0.0f, 0.2f, 0.0f, 0.08f, 0.0f, true },
            },
        },
    },
};

static const PdnaInstrumentVoicePreset song_1_harmony_voices[] = {
    {
        .key_range = { 0.0f, 127.0f },
        .voice = {
            .waveform = PDNA_WAVEFORM_TRIANGLE,
            .envelope = { 0.005f, 0.04f, 0.55f, 0.03f, 0.0f, 1.0f, false, true, NULL },
            .volume = 0.35f,
            .pitch_source = { .kind = PDNA_PITCH_SOURCE_NONE },
        },
    },
};

static const PdnaInstrumentVoicePreset song_1_bass_voices[] = {
    {
        .key_range = { 0.0f, 127.0f },
        .voice = {
            .waveform = PDNA_WAVEFORM_SAWTOOTH,
            .envelope = { 0.005f, 0.04f, 0.55f, 0.5f, 0.0f, 1.0f, false, true, NULL },
            .volume = 0.2f,
            .pitch_source = { .kind = PDNA_PITCH_SOURCE_NONE },
        },
    },
};

static const PdnaInstrumentVoicePreset song_1_percussion_voices[] = {
    {
        .key_range = { 36.0f, 36.0f },
        .voice = {
            .waveform = PDNA_WAVEFORM_NOISE,
            .envelope = { 0.001f, 0.08f, 0.0f, 0.04f, 0.0f, 1.0f, false, true, NULL },
            .volume = 0.35f,
            .pitch_source = { .kind = PDNA_PITCH_SOURCE_NONE },
        },
    },
    {
        .key_range = { 35.0f, 35.0f },
        .voice = {
            .waveform = PDNA_WAVEFORM_SQUARE,
            .envelope = { 0.001f, 0.04f, 0.0f, 0.003f, 0.0f, 1.0f, false, true, NULL },
            .volume = 0.35f,
            .pitch_source = { .kind = PDNA_PITCH_SOURCE_NONE },
        },
    },
    {
        .key_range = { 37.0f, 126.0f },
        .voice = {
            .waveform = PDNA_WAVEFORM_SQUARE,
            .envelope = { 0.005f, 0.04f, 0.55f, 0.03f, 0.0f, 1.0f, false, true, NULL },
            .volume = 0.12f,
            .pitch_source = { .kind = PDNA_PITCH_SOURCE_NONE },
        },
    },
    {
        .key_range = { 0.0f, 34.0f },
        .voice = {
            .waveform = PDNA_WAVEFORM_SQUARE,
            .envelope = { 0.005f, 0.04f, 0.55f, 0.03f, 0.0f, 1.0f, false, true, NULL },
            .volume = 0.12f,
            .pitch_source = { .kind = PDNA_PITCH_SOURCE_NONE },
        },
    },
    {
        .key_range = { 127.0f, 127.0f },
        .voice = {
            .waveform = PDNA_WAVEFORM_SQUARE,
            .envelope = { 0.005f, 0.04f, 0.55f, 0.03f, 0.0f, 1.0f, false, true, NULL },
            .volume = 0.12f,
            .pitch_source = { .kind = PDNA_PITCH_SOURCE_NONE },
        },
    },
};

const PdnaSongPreset pdna_song_1 = {
    .steps_per_second = 6.6666665f,
    .length_steps = 64,
    .loop_start_step = 0,
    .loop_end_step_inclusive = 63,
    .tracks = {
        {
            .volume = 1.0f,
            .voices = song_1_lead_voices,
            .voice_count = sizeof(song_1_lead_voices) / sizeof(song_1_lead_voices[0]),
            .notes = song_1_lead_notes,
            .note_count = sizeof(song_1_lead_notes) / sizeof(song_1_lead_notes[0]),
        },
        {
            .volume = 1.0f,
            .voices = song_1_harmony_voices,
            .voice_count = sizeof(song_1_harmony_voices) / sizeof(song_1_harmony_voices[0]),
            .notes = song_1_harmony_notes,
            .note_count = sizeof(song_1_harmony_notes) / sizeof(song_1_harmony_notes[0]),
        },
        {
            .volume = 1.0f,
            .voices = song_1_bass_voices,
            .voice_count = sizeof(song_1_bass_voices) / sizeof(song_1_bass_voices[0]),
            .notes = song_1_bass_notes,
            .note_count = sizeof(song_1_bass_notes) / sizeof(song_1_bass_notes[0]),
        },
        {
            .volume = 1.0f,
            .voices = song_1_percussion_voices,
            .voice_count = sizeof(song_1_percussion_voices) / sizeof(song_1_percussion_voices[0]),
            .notes = song_1_percussion_notes,
            .note_count = sizeof(song_1_percussion_notes) / sizeof(song_1_percussion_notes[0]),
        },
    },
};
