#ifndef PDNA_EFFECTS_H
#define PDNA_EFFECTS_H

#include "pdna_audio.h"

/* Generated by PDNA. Do not edit by hand; edit the .pdna.json source. */
extern const PdnaEffectPreset pdna_effect_stack_land;
extern const PdnaEffectPreset pdna_effect_perfect_stack;
extern const PdnaEffectPreset pdna_effect_perfect_stack_2;
extern const PdnaEffectPreset pdna_effect_perfect_growth;
extern const PdnaEffectPreset pdna_effect_stack_miss;

#endif
